namespace: team-worksonourmachines

ingress:
  host: team-worksonourmachines.stud.k8s.aet.cit.tum.de

ai:
  image: ghcr.io/aet-devops26/team-worksonourmachines/ai:latest
  llmProvider: logos
  llmBaseUrl: https://logos.aet.cit.tum.de
  llmModel: openai/gpt-oss-120b
  llmApiKey: ""  # Set via --set ai.llmApiKey=lg-...

clientWeb:
  image: ghcr.io/aet-devops26/team-worksonourmachines/client-web:latest
  serverCommunicationApiUrl: tbd
  serverMarketplaceApiUrl: tbd
  serverStudentApiUrl: tbd
