name: tutormatch

services:
  client-web:
    build:
      context: .
      dockerfile: artifacts/client-web/docker/Dockerfile
      target: dev
    volumes:
      - ./artifacts/client-web:/app:Z
      - client-web-node-modules:/app/node_modules
    ports:
      - 5173:5173
    environment:
      LOG_FORMAT: ${CLIENT_WEB_LOG_FORMAT:-json}
      LOG_LEVEL: ${CLIENT_WEB_LOG_LEVEL:-info}
      SERVER_COMMUNICATION_API_URL: tbd
      SERVER_MARKETPLACE_API_URL: tbd
      SERVER_STUDENT_API_URL: tbd

  ai:
    build:
      context: .
      dockerfile: artifacts/ai/docker/Dockerfile
      target: dev
    volumes:
      - ./artifacts/ai:/app:Z
    ports:
      - 8000:8000
    environment:
      LOG_LEVEL: ${AI_LOG_LEVEL:-INFO}
      OPENAI_API_KEY: ${OPENAI_API_KEY:-}
      OLLAMA_BASE_URL: ${OLLAMA_BASE_URL:-http://ollama:11434}
    depends_on:
      - ollama

  ollama:
    image: ollama/ollama:latest
    volumes:
      - ollama_data:/root/.ollama
    ports:
      - 11434:11434

  # ----------------------------- tooling -----------------------------

  api-tooling:
    profiles: ["tooling"]
    build:
      context: .
      dockerfile: api/docker/Dockerfile
    user: "${HOST_UID:-1000}:${HOST_GID:-1000}"
    userns_mode: keep-id
    environment:
      CI: "true"
    volumes:
      - ./api:/workspace/api:Z
      - pnpm-store:/pnpm/store

  client-web-tooling:
    profiles: ["tooling"]
    build:
      context: .
      dockerfile: artifacts/client-web/docker/Dockerfile
      target: tooling
    user: "${HOST_UID:-1000}:${HOST_GID:-1000}"
    userns_mode: keep-id
    environment:
      CI: "true"
    volumes:
      - ./artifacts/client-web:/workspace/artifacts/client-web:Z
      - ./.git:/workspace/.git:Z # git mounts necessary for biome
      - ./.gitignore:/workspace/.gitignore:Z
      - pnpm-store:/pnpm/store

  ai-tooling:
    profiles: ["tooling"]
    build:
      context: .
      dockerfile: artifacts/ai/docker/Dockerfile
      target: tooling
    user: "${HOST_UID:-1000}:${HOST_GID:-1000}"
    userns_mode: keep-id
    volumes:
      - ./artifacts/ai:/workspace/artifacts/ai:Z
      - /workspace/artifacts/ai/.venv # prevent venv from overriding host venv

volumes:
  pnpm-store:
  client-web-node-modules:
  ollama_data: