services:
  api-tooling:
    build:
      context: .
      dockerfile: api/docker/Dockerfile
    user: "${HOST_UID:-1000}:${HOST_GID:-1000}"
    userns_mode: keep-id
    environment:
      CI: "true"
    volumes:
      - ./:/workspace/:Z
      - pnpm-store:/pnpm/store

  client-web-tooling:
    build:
      context: .
      dockerfile: artifacts/client-web/docker/Dockerfile
      target: tooling
    user: "${HOST_UID:-1000}:${HOST_GID:-1000}"
    userns_mode: keep-id
    environment:
      CI: "true"
    volumes:
      - ./artifacts/client-web:/workspace/artifacts/client-web:Z
      - ./.git:/workspace/.git:Z # git mounts necessary for biome
      - ./.gitignore:/workspace/.gitignore:Z
      - pnpm-store:/pnpm/store

  ai-tooling:
    build:
      context: .
      dockerfile: artifacts/ai/docker/Dockerfile
      target: tooling
    user: "${HOST_UID:-1000}:${HOST_GID:-1000}"
    userns_mode: keep-id
    volumes:
      - ./artifacts/ai:/workspace/artifacts/ai:Z
      - /workspace/artifacts/ai/.venv # prevent venv from overriding host venv

volumes:
  pnpm-store:
