name: tutormatch

services:
  client-web:
    build:
      context: .
      dockerfile: artifacts/client-web/Dockerfile
      target: dev
    volumes:
      - ./artifacts/client-web:/app:Z
      - client-web-node-modules:/app/node_modules
    ports:
      - 5173:5173
    environment:
      LOG_FORMAT: ${CLIENT_WEB_LOG_FORMAT:-json}
      LOG_LEVEL: ${CLIENT_WEB_LOG_LEVEL:-info}
      SERVER_COMMUNICATION_API_URL: tbd
      SERVER_MARKETPLACE_API_URL: tbd
      SERVER_STUDENT_API_URL: tbd

  client-web-tooling:
    profiles: ["tooling"]
    build:
      context: .
      dockerfile: artifacts/client-web/Dockerfile
      target: tooling
    user: "${HOST_UID:-1000}:${HOST_GID:-1000}"
    userns_mode: keep-id
    environment:
      - CI=true
    volumes:
      - ./artifacts/client-web:/workspace/artifacts/client-web:Z
      - ./.git:/workspace/.git:Z
      - ./.gitignore:/workspace/.gitignore:Z
      - pnpm-store:/pnpm/store

  api-tooling:
    profiles: ["tooling"]
    build:
      context: .
      dockerfile: api/Dockerfile
    user: "${HOST_UID:-1000}:${HOST_GID:-1000}"
    userns_mode: keep-id
    environment:
      - CI=true
    volumes:
      - ./api:/workspace/api:Z
      - pnpm-store:/pnpm/store

volumes:
  pnpm-store:
  client-web-node-modules:
