{
 "title": "Spring Boot Observability",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "app_name", "label": "Application Name", "query": { "query": "label_values(job)" } },
   { "name": "log_keyword", "label": "Log Query" }
  ]
 },
 "panels": [
  {
   "title": "Requests in Selected Time Range",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (job) (increase(http_server_requests_seconds_count{job=~\"$app_name\", uri!=\"/actuator/prometheus\"}[$__range]))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Requests Count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (job, method, uri) (http_server_requests_seconds_count{job=~\"$app_name\", uri!=\"/actuator/prometheus\"})",
     "legendFormat": "{{job}} {{method}} {{uri}}"
    }
   ]
  },
  {
   "title": "Requests Average Duration",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (job, method, uri) (http_server_requests_seconds_sum{job=~\"$app_name\", uri!=\"/actuator/prometheus\"}) / sum by (job, method, uri) (http_server_requests_seconds_count{job=~\"$app_name\", uri!=\"/actuator/prometheus\"})",
     "legendFormat": "{{job}} {{method}} {{uri}}"
    }
   ]
  },
  {
   "title": "Server Error Requests",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum by (job) (http_server_requests_seconds_count{job=~\"$app_name\", outcome=\"SERVER_ERROR\", uri!=\"/actuator/prometheus\"}) or on (job) (0 * sum by (job) (http_server_requests_seconds_count{job=~\"$app_name\", uri!=\"/actuator/prometheus\"})))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "2xx Request Ratio",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(sum by (job) (http_server_requests_seconds_count{job=~\"$app_name\", status=~\"2..\", uri!=\"/actuator/prometheus\"}) or on (job) (0 * sum by (job) (http_server_requests_seconds_count{job=~\"$app_name\", uri!=\"/actuator/prometheus\"}))) / sum by (job) (http_server_requests_seconds_count{job=~\"$app_name\", uri!=\"/actuator/prometheus\"})",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "5xx Request Ratio",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(sum by (job) (http_server_requests_seconds_count{job=~\"$app_name\", status=~\"5..\", uri!=\"/actuator/prometheus\"}) or on (job) (0 * sum by (job) (http_server_requests_seconds_count{job=~\"$app_name\", uri!=\"/actuator/prometheus\"}))) / sum by (job) (http_server_requests_seconds_count{job=~\"$app_name\", uri!=\"/actuator/prometheus\"})",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "P99 Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (job, uri, le) (rate(http_server_requests_seconds_bucket{job=~\"$app_name\", uri!=\"/actuator/prometheus\"}[1h])))",
     "legendFormat": "{{job}} {{uri}}"
    }
   ]
  },
  {
   "title": "P95 Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (job, uri, le) (rate(http_server_requests_seconds_bucket{job=~\"$app_name\", uri!=\"/actuator/prometheus\"}[1h])))",
     "legendFormat": "{{job}} {{uri}}"
    }
   ]
  },
  {
   "title": "Requests per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (job, uri) (rate(http_server_requests_seconds_count{job=~\"$app_name\", uri!=\"/actuator/prometheus\"}[1h]))",
     "legendFormat": "{{job}} {{uri}}"
    }
   ]
  },
  {
   "title": "Log Type Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 21 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (service_name, type) (rate({service_name=~\"$app_name\"} | pattern `<timestamp> <_> <type> <pid> --- [<application>] [<thread>] <logger> : <msg>` | type =~ \"TRACE|DEBUG|INFO|WARN|ERROR\" |~ \"$log_keyword\" [1h]))",
     "legendFormat": "{{service_name}} {{type}}"
    }
   ]
  },
  {
   "title": "Log of All Spring Boot Apps",
   "type": "logs",
   "gridPos": { "h": 9, "w": 18, "x": 6, "y": 21 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=~\"$app_name\"} | pattern `<timestamp> <_> <level> <pid> --- [<application>] [<thread>] <logger> : <message>` | level =~ \"TRACE|DEBUG|INFO|WARN|ERROR\" |~ \"$log_keyword\" | line_format \"{{.service_name}}\\t{{.level}}\\t{{.message}}\""
    }
   ]
  }
 ]
}