openapi: 3.0.0
info:
  title: Student API
  version: v1
servers:
- description: Student API
  url: https://student.example.local
security:
- KeycloakBearerAuth: []
paths:
  /v1/test:
    get:
      operationId: test
      parameters: []
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/test_200_response"
          description: The request has succeeded.
      x-accepts:
      - application/json
components:
  schemas:
    test_200_response:
      example:
        message: message
      properties:
        message:
          type: string
      required:
      - message
      type: object
  securitySchemes:
    KeycloakBearerAuth:
      description: Keycloak access token issued to the BFF client
      scheme: Bearer
      type: http
