openapi: 3.0.0
info:
  title: Module2 API
  version: v1
servers:
- description: Module2 API
  url: https://module2.example.com
paths:
  /v1/test:
    get:
      operationId: test
      parameters: []
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/test_200_response"
          description: The request has succeeded.
      x-accepts:
      - application/json
components:
  schemas:
    test_200_response:
      example:
        message: message
      properties:
        message:
          type: string
      required:
      - message
      type: object
