alertmanager:
  enabled: false
prometheus-node-exporter:
  enabled: false
kube-state-metrics:
  enabled: false
prometheus-pushgateway:
  enabled: false
rbac:
  create: false
server:
  fullnameOverride: prometheus
  service:
    servicePort: 9090
  persistentVolume:
    enabled: false
  global:
    scrape_interval: 10s
  resources:
    requests:
      cpu: 25m
      memory: 128Mi
    limits:
      cpu: 50m
      memory: 256Mi
configmapReload:
  prometheus:
    resources:
      requests:
        cpu: 10m
        memory: 16Mi
      limits:
        cpu: 25m
        memory: 32Mi
serverFiles:
  prometheus.yml:
    scrape_configs:
      - job_name: spring-boot-services
        metrics_path: /actuator/prometheus
        kubernetes_sd_configs:
          - role: endpoints
            namespaces:
              names: ["team-worksonourmachines"]
        relabel_configs:
          - source_labels: [__meta_kubernetes_service_name]
            regex: "server-(student|marketplace|communication)"
            action: keep
          - source_labels: [__meta_kubernetes_service_name]
            target_label: job

extraScrapeConfigs: |
  - job_name: ai
    metrics_path: /metrics
    static_configs:
      - targets: ["ai:8000"]

  - job_name: kube-state-metrics
    static_configs:
      - targets: ["kube-state-metrics:8080"]
